cat("Affy analysis GX pipeline\n")
cat("Starting main analysis\n")
source("affy_pipeline1.R")
cat("Analysis done, starting report generation\n")
library(knitr)
knit("Reports/GX_Affy_report_full.Rnw")
cat("Generating pdf\n")
system("pdflatex GX_Affy_report_full.tex")
cat("Analysis completed and report generated\n")